### PR TITLE
Fix deploy to Heroku button

### PR DESCRIPTION
**Pull request by konyu**
This PR resolves this Issue #9

There have already been other PRs against for the same issue.
But the minimum PostgreSQL plan's name in Heroku was changed again.

### CODE REVIEW

**Comment by sinanmohd** [comment]
Thanks so much for fixing the issue, Could you please squash all the commits.
also if possible change the commit message to

fix(heroku): change postgresql plan to essential-0

the hobby-dev postgresql plan is no longer available
https://devcenter.heroku.com/changelog-items/2502

**Comment by konyu** [comment]
@sinanmohd

> Could you please squash all the commits.

Done!!

**Review by sinanmohd — CHANGES_REQUESTED** [review]
nicely done, if you need help with updating the commit message

$ GIT_EDITOR=code git commit --amend
-> replace the text with, save & exit
```
fix(heroku): change postgresql plan to essential-0

the hobby-dev postgresql plan is no longer available
https://devcenter.heroku.com/changelog-items/2502
```
$ git push -f

**Comment by konyu** [comment]
@sinanmohd I see, I'm totally done with it.

**Review by sinanmohd — APPROVED** [review]

**Pull request merged**
